name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pack-lua-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/pack
        with:
          resources: |
            experiment_soft_dependencies
      - name: Upload zip files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./resources/*/*.zip
  build-and-pack-javascript-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: ./.github/actions/pack
        with:
          resources: |
            experiment_versioned_dependencies
      - name: Upload zip files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./resources/*/*.zip
