name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pack-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/pack-action.yml
        with: |
          experiment_soft_dependencies
      - name: Upload zip files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*/*.zip
